name: Bug report
description: Report an bug in OpenSlide
labels: ["defect"]
body:
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Fedora 37, macOS 12, Windows 11
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: e.g. 64-bit x86, 32-bit ARM
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenSlide version
    validations:
      required: true
  - type: input
    id: format
    attributes:
      label: Slide format
      placeholder: e.g. SVS, NDPI, MRXS
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Issue details
      placeholder: Describe your issue
    validations:
      required: true
